spring:
  application:
    name: nacos-spring-boot-confg-example
  profiles:
    active: dev # 表示开发环境
#    active: test # 表示测试环境
#    active: info


server:
  port: 8081



nacos:
  config:
    server-addr: 127.0.0.1:8848