package com.animal.farm.familytree;

import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.stream.Collectors;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.animal.farm.familytree.controller.ApiController;
import com.animal.farm.familytree.dto.FamilyTreeNode;
import com.animal.farm.familytree.dto.FamilyTreeNodeNew;
import com.animal.farm.familytree.infrastructure.util.JsonUtil;

/**
 * @author guojun
 * @date 2023/10/11 15:57
 */

@TestInstance(Lifecycle.PER_CLASS)
public class TestTreeOps {
  private static final Logger LOGGER = LoggerFactory.getLogger(TestTreeOps.class);

  private String jsonStr = "["
      + "        {\n"
      + "            \"id\": 1, \n"
      + "            \"code\": \"1\", \n"
      + "            \"name\": \"钟敬\", \n"
      + "            \"mark\": \"久也\", \n"
      + "            \"parentCode\": -1, \n"
      + "            \"parentName\": null, \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"康熙戊戌 五十七年 生子三：梅楷桂\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 2, \n"
      + "            \"code\": \"11\", \n"
      + "            \"name\": \"洪梅\", \n"
      + "            \"mark\": \"占鳌\", \n"
      + "            \"parentCode\": 1, \n"
      + "            \"parentName\": \"钟敬\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"乾隆辛未十六年 生子三：隽雄质\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 3, \n"
      + "            \"code\": \"12\", \n"
      + "            \"name\": \"洪楷\", \n"
      + "            \"mark\": \"占魁\", \n"
      + "            \"parentCode\": 1, \n"
      + "            \"parentName\": \"钟敬\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"乾隆十九年 生子二：达艺\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 4, \n"
      + "            \"code\": \"13\", \n"
      + "            \"name\": \"洪桂\", \n"
      + "            \"mark\": \"占元\", \n"
      + "            \"parentCode\": 1, \n"
      + "            \"parentName\": \"钟敬\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"乾隆二十三年 五子：圣仁申棠悔\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 5, \n"
      + "            \"code\": \"111\", \n"
      + "            \"name\": \"材隽\", \n"
      + "            \"mark\": \"最纯\", \n"
      + "            \"parentCode\": 11, \n"
      + "            \"parentName\": \"洪梅\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"乾隆癸已三十八年 生子一： 章\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 6, \n"
      + "            \"code\": \"112\", \n"
      + "            \"name\": \"材雄\", \n"
      + "            \"mark\": \"亦纯\", \n"
      + "            \"parentCode\": 11, \n"
      + "            \"parentName\": \"洪梅\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"乾隆四十二年 生子二：襄赞\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 7, \n"
      + "            \"code\": \"113\", \n"
      + "            \"name\": \"材质\", \n"
      + "            \"mark\": \"愈纯\", \n"
      + "            \"parentCode\": 11, \n"
      + "            \"parentName\": \"洪梅\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"乾隆四十四年 生子二： 承裕\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 8, \n"
      + "            \"code\": \"1131\", \n"
      + "            \"name\": \"烈承\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 113, \n"
      + "            \"parentName\": \"材质\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"嘉庆十三年 生子二： 镜德\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 9, \n"
      + "            \"code\": \"1132\", \n"
      + "            \"name\": \"烈裕\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 113, \n"
      + "            \"parentName\": \"材质\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"道光四年 生子二： 模鑑\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 10, \n"
      + "            \"code\": \"11321\", \n"
      + "            \"name\": \"在模\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1132, \n"
      + "            \"parentName\": \"烈裕\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"道光二十六年  被匪掳去 无子 嗣一子 润\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 11, \n"
      + "            \"code\": \"11322\", \n"
      + "            \"name\": \"在鑑\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1132, \n"
      + "            \"parentName\": \"烈裕\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"咸丰四年  娶胡氏 生子六： 润澜闻开闵闲\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 12, \n"
      + "            \"code\": \"113221\", \n"
      + "            \"name\": \"锡润\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11322, \n"
      + "            \"parentName\": \"在鑑\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 13, \n"
      + "            \"code\": \"113222\", \n"
      + "            \"name\": \"锡澜\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11322, \n"
      + "            \"parentName\": \"在鑑\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 14, \n"
      + "            \"code\": \"113223\", \n"
      + "            \"name\": \"锡闻\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11322, \n"
      + "            \"parentName\": \"在鑑\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 15, \n"
      + "            \"code\": \"113224\", \n"
      + "            \"name\": \"锡开\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11322, \n"
      + "            \"parentName\": \"在鑑\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 16, \n"
      + "            \"code\": \"113225\", \n"
      + "            \"name\": \"锡闵\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11322, \n"
      + "            \"parentName\": \"在鑑\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 17, \n"
      + "            \"code\": \"113226\", \n"
      + "            \"name\": \"锡闲\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11322, \n"
      + "            \"parentName\": \"在鑑\", \n"
      + "            \"sort\": 6, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 18, \n"
      + "            \"code\": \"1132231\", \n"
      + "            \"name\": \"泰章\", \n"
      + "            \"mark\": \"冬生\", \n"
      + "            \"parentCode\": 113223, \n"
      + "            \"parentName\": \"锡闻\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 19, \n"
      + "            \"code\": \"1132232\", \n"
      + "            \"name\": \"泰耀\", \n"
      + "            \"mark\": \"水全\", \n"
      + "            \"parentCode\": 113223, \n"
      + "            \"parentName\": \"锡闻\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 20, \n"
      + "            \"code\": \"11322311\", \n"
      + "            \"name\": \"楙涛\", \n"
      + "            \"mark\": \"黑巴\", \n"
      + "            \"parentCode\": 1132231, \n"
      + "            \"parentName\": \"泰章\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 21, \n"
      + "            \"code\": \"11322312\", \n"
      + "            \"name\": \"楙雨\", \n"
      + "            \"mark\": \"志涛\", \n"
      + "            \"parentCode\": 1132231, \n"
      + "            \"parentName\": \"泰章\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 22, \n"
      + "            \"code\": \"113223111\", \n"
      + "            \"name\": \"熙俊\", \n"
      + "            \"mark\": \"俊\", \n"
      + "            \"parentCode\": 11322311, \n"
      + "            \"parentName\": \"楙涛\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 23, \n"
      + "            \"code\": \"113223112\", \n"
      + "            \"name\": \"熙杰\", \n"
      + "            \"mark\": \"杰\", \n"
      + "            \"parentCode\": 11322311, \n"
      + "            \"parentName\": \"楙涛\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 24, \n"
      + "            \"code\": \"113223121\", \n"
      + "            \"name\": \"熙冲\", \n"
      + "            \"mark\": \"冲\", \n"
      + "            \"parentCode\": 11322312, \n"
      + "            \"parentName\": \"楙雨\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 25, \n"
      + "            \"code\": \"113223122\", \n"
      + "            \"name\": \"熙勇\", \n"
      + "            \"mark\": \"号\", \n"
      + "            \"parentCode\": 11322312, \n"
      + "            \"parentName\": \"楙雨\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 26, \n"
      + "            \"code\": \"1121\", \n"
      + "            \"name\": \"烈襄\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112, \n"
      + "            \"parentName\": \"材雄\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"嘉庆六年 生子二：仪善\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 27, \n"
      + "            \"code\": \"1122\", \n"
      + "            \"name\": \"烈赞\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112, \n"
      + "            \"parentName\": \"材雄\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"嘉庆十二年 殁于嘉庆二十年 无子\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 28, \n"
      + "            \"code\": \"11211\", \n"
      + "            \"name\": \"在仪\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121, \n"
      + "            \"parentName\": \"烈襄\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"道光十七年 生子二： 藻宗\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 29, \n"
      + "            \"code\": \"11212\", \n"
      + "            \"name\": \"在善\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121, \n"
      + "            \"parentName\": \"烈襄\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"道光二十年 生子四：椿枫槐梧\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 30, \n"
      + "            \"code\": \"112111\", \n"
      + "            \"name\": \"锡藻\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11211, \n"
      + "            \"parentName\": \"在仪\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 31, \n"
      + "            \"code\": \"112112\", \n"
      + "            \"name\": \"锡宗\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11211, \n"
      + "            \"parentName\": \"在仪\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 32, \n"
      + "            \"code\": \"112121\", \n"
      + "            \"name\": \"锡椿\", \n"
      + "            \"mark\": \"体仁\", \n"
      + "            \"parentCode\": 11212, \n"
      + "            \"parentName\": \"在善\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 33, \n"
      + "            \"code\": \"112122\", \n"
      + "            \"name\": \"锡枫\", \n"
      + "            \"mark\": \"咏仁\", \n"
      + "            \"parentCode\": 11212, \n"
      + "            \"parentName\": \"在善\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 34, \n"
      + "            \"code\": \"112123\", \n"
      + "            \"name\": \"锡槐\", \n"
      + "            \"mark\": \"怀仁\", \n"
      + "            \"parentCode\": 11212, \n"
      + "            \"parentName\": \"在善\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 35, \n"
      + "            \"code\": \"112124\", \n"
      + "            \"name\": \"锡梧\", \n"
      + "            \"mark\": \"安仁\", \n"
      + "            \"parentCode\": 11212, \n"
      + "            \"parentName\": \"在善\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 36, \n"
      + "            \"code\": \"1121121\", \n"
      + "            \"name\": \"泰安\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112112, \n"
      + "            \"parentName\": \"锡宗\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 37, \n"
      + "            \"code\": \"1121122\", \n"
      + "            \"name\": \"泰宙\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112112, \n"
      + "            \"parentName\": \"锡宗\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 38, \n"
      + "            \"code\": \"11211221\", \n"
      + "            \"name\": \"楙棋\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121122, \n"
      + "            \"parentName\": \"泰宙\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 39, \n"
      + "            \"code\": \"11211222\", \n"
      + "            \"name\": \"楙恒\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121122, \n"
      + "            \"parentName\": \"泰宙\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 40, \n"
      + "            \"code\": \"1121123\", \n"
      + "            \"name\": \"泰宣\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112112, \n"
      + "            \"parentName\": \"锡宗\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 41, \n"
      + "            \"code\": \"11211231\", \n"
      + "            \"name\": \"楙潜\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121123, \n"
      + "            \"parentName\": \"泰宣\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 42, \n"
      + "            \"code\": \"11211232\", \n"
      + "            \"name\": \"楙富\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121123, \n"
      + "            \"parentName\": \"泰宣\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 43, \n"
      + "            \"code\": \"11211233\", \n"
      + "            \"name\": \"楙贵\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121123, \n"
      + "            \"parentName\": \"泰宣\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 44, \n"
      + "            \"code\": \"1121124\", \n"
      + "            \"name\": \"泰容\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112112, \n"
      + "            \"parentName\": \"锡宗\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 45, \n"
      + "            \"code\": \"11211241\", \n"
      + "            \"name\": \"楙修\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121124, \n"
      + "            \"parentName\": \"泰容\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 46, \n"
      + "            \"code\": \"11211242\", \n"
      + "            \"name\": \"楙华\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121124, \n"
      + "            \"parentName\": \"泰容\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 47, \n"
      + "            \"code\": \"11211243\", \n"
      + "            \"name\": \"楙福\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121124, \n"
      + "            \"parentName\": \"泰容\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 48, \n"
      + "            \"code\": \"112112411\", \n"
      + "            \"name\": \"熙圣\", \n"
      + "            \"mark\": \"焕章\", \n"
      + "            \"parentCode\": 11211241, \n"
      + "            \"parentName\": \"楙修\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 49, \n"
      + "            \"code\": \"1121124111\", \n"
      + "            \"name\": \"培洪\", \n"
      + "            \"mark\": \"早生\", \n"
      + "            \"parentCode\": 112112411, \n"
      + "            \"parentName\": \"熙圣\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1964\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 50, \n"
      + "            \"code\": \"1121124112\", \n"
      + "            \"name\": \"培武\", \n"
      + "            \"mark\": \"水生\", \n"
      + "            \"parentCode\": 112112411, \n"
      + "            \"parentName\": \"熙圣\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 51, \n"
      + "            \"code\": \"112112421\", \n"
      + "            \"name\": \"熙正\", \n"
      + "            \"mark\": \"正佳（告花）\", \n"
      + "            \"parentCode\": 11211242, \n"
      + "            \"parentName\": \"楙华\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 52, \n"
      + "            \"code\": \"112112422\", \n"
      + "            \"name\": \"熙磊\", \n"
      + "            \"mark\": \"镇平\", \n"
      + "            \"parentCode\": 11211242, \n"
      + "            \"parentName\": \"楙华\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 53, \n"
      + "            \"code\": \"1121125\", \n"
      + "            \"name\": \"泰家\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112112, \n"
      + "            \"parentName\": \"锡宗\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 54, \n"
      + "            \"code\": \"11211251\", \n"
      + "            \"name\": \"楙和\", \n"
      + "            \"mark\": \"寿元\", \n"
      + "            \"parentCode\": 1121125, \n"
      + "            \"parentName\": \"泰家\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 55, \n"
      + "            \"code\": \"11211252\", \n"
      + "            \"name\": \"楙亨\", \n"
      + "            \"mark\": \"金元\", \n"
      + "            \"parentCode\": 1121125, \n"
      + "            \"parentName\": \"泰家\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 56, \n"
      + "            \"code\": \"1121211\", \n"
      + "            \"name\": \"泰丕\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112121, \n"
      + "            \"parentName\": \"锡椿\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 57, \n"
      + "            \"code\": \"1121212\", \n"
      + "            \"name\": \"泰冲\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112121, \n"
      + "            \"parentName\": \"锡椿\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 58, \n"
      + "            \"code\": \"1121213\", \n"
      + "            \"name\": \"泰敏\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112121, \n"
      + "            \"parentName\": \"锡椿\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 59, \n"
      + "            \"code\": \"1121214\", \n"
      + "            \"name\": \"泰尙\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112121, \n"
      + "            \"parentName\": \"锡椿\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"光绪二十八年 生子三： 福禄寿\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 60, \n"
      + "            \"code\": \"1121215\", \n"
      + "            \"name\": \"泰进\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112121, \n"
      + "            \"parentName\": \"锡椿\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 61, \n"
      + "            \"code\": \"11212131\", \n"
      + "            \"name\": \"楙楷\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121213, \n"
      + "            \"parentName\": \"泰敏\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 62, \n"
      + "            \"code\": \"11212132\", \n"
      + "            \"name\": \"楙梁\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1121213, \n"
      + "            \"parentName\": \"泰敏\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 63, \n"
      + "            \"code\": \"112121311\", \n"
      + "            \"name\": \"熙华\", \n"
      + "            \"mark\": \"志华\", \n"
      + "            \"parentCode\": 11212131, \n"
      + "            \"parentName\": \"楙楷\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 64, \n"
      + "            \"code\": \"112121312\", \n"
      + "            \"name\": \"熙辉\", \n"
      + "            \"mark\": \"志辉\", \n"
      + "            \"parentCode\": 11212131, \n"
      + "            \"parentName\": \"楙楷\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 65, \n"
      + "            \"code\": \"112121321\", \n"
      + "            \"name\": \"熙高\", \n"
      + "            \"mark\": \"建洪\", \n"
      + "            \"parentCode\": 11212132, \n"
      + "            \"parentName\": \"楙梁\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 66, \n"
      + "            \"code\": \"1121214121\", \n"
      + "            \"name\": \"培花\", \n"
      + "            \"mark\": \"建新\", \n"
      + "            \"parentCode\": 112121412, \n"
      + "            \"parentName\": \"熙桂（春生）\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 67, \n"
      + "            \"code\": \"1121214122\", \n"
      + "            \"name\": \"培友\", \n"
      + "            \"mark\": \"建华\", \n"
      + "            \"parentCode\": 112121412, \n"
      + "            \"parentName\": \"熙桂（春生）\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 68, \n"
      + "            \"code\": \"112121423\", \n"
      + "            \"name\": \"熙正\", \n"
      + "            \"mark\": \"水生\", \n"
      + "            \"parentCode\": 11212142, \n"
      + "            \"parentName\": \"楙禄\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"黑八 1962\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 69, \n"
      + "            \"code\": \"1121214231\", \n"
      + "            \"name\": \"培祖\", \n"
      + "            \"mark\": \"晶晶\", \n"
      + "            \"parentCode\": 112121423, \n"
      + "            \"parentName\": \"熙正\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1983\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 70, \n"
      + "            \"code\": \"112112521\", \n"
      + "            \"name\": \"熙灿\", \n"
      + "            \"mark\": \"灿先\", \n"
      + "            \"parentCode\": 11211252, \n"
      + "            \"parentName\": \"楙亨\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 71, \n"
      + "            \"code\": \"112112522\", \n"
      + "            \"name\": \"熙江\", \n"
      + "            \"mark\": \"毛头\", \n"
      + "            \"parentCode\": 11211252, \n"
      + "            \"parentName\": \"楙亨\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 72, \n"
      + "            \"code\": \"112112523\", \n"
      + "            \"name\": \"熙秦\", \n"
      + "            \"mark\": \"灿国\", \n"
      + "            \"parentCode\": 11211252, \n"
      + "            \"parentName\": \"楙亨\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 73, \n"
      + "            \"code\": \"112112524\", \n"
      + "            \"name\": \"熙峰\", \n"
      + "            \"mark\": \"灿全\", \n"
      + "            \"parentCode\": 11211252, \n"
      + "            \"parentName\": \"楙亨\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 74, \n"
      + "            \"code\": \"121\", \n"
      + "            \"name\": \"材达\", \n"
      + "            \"mark\": \"学智\", \n"
      + "            \"parentCode\": 12, \n"
      + "            \"parentName\": \"洪楷\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"乾隆三十九年 生子六：瑞与兴仁声珍\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 75, \n"
      + "            \"code\": \"122\", \n"
      + "            \"name\": \"材艺\", \n"
      + "            \"mark\": \"学能\", \n"
      + "            \"parentCode\": 12, \n"
      + "            \"parentName\": \"洪楷\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"乾隆四十三年 生子一： 瑛\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 76, \n"
      + "            \"code\": \"1221\", \n"
      + "            \"name\": \"烈瑛\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 122, \n"
      + "            \"parentName\": \"材艺\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"嘉庆戊辰十三年 生子四：文武全荣\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 77, \n"
      + "            \"code\": \"12211\", \n"
      + "            \"name\": \"在文\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1221, \n"
      + "            \"parentName\": \"烈瑛\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"道光十一年  殁于光绪十年 生子三：承瀛治\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 78, \n"
      + "            \"code\": \"12212\", \n"
      + "            \"name\": \"在武\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1221, \n"
      + "            \"parentName\": \"烈瑛\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"道光十四年 殁于光绪三十年 生子四：魁甲榜名\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 79, \n"
      + "            \"code\": \"12213\", \n"
      + "            \"name\": \"在全\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1221, \n"
      + "            \"parentName\": \"烈瑛\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"生子二：刚方\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 80, \n"
      + "            \"code\": \"12214\", \n"
      + "            \"name\": \"在荣\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1221, \n"
      + "            \"parentName\": \"烈瑛\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"生子三：辉阳垣\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 81, \n"
      + "            \"code\": \"122111\", \n"
      + "            \"name\": \"锡承\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 12211, \n"
      + "            \"parentName\": \"在文\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 82, \n"
      + "            \"code\": \"122112\", \n"
      + "            \"name\": \"锡瀛\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 12211, \n"
      + "            \"parentName\": \"在文\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 83, \n"
      + "            \"code\": \"122113\", \n"
      + "            \"name\": \"锡治\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 12211, \n"
      + "            \"parentName\": \"在文\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 84, \n"
      + "            \"code\": \"122121\", \n"
      + "            \"name\": \"锡魁\", \n"
      + "            \"mark\": \"锦标\", \n"
      + "            \"parentCode\": 12212, \n"
      + "            \"parentName\": \"在武\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 85, \n"
      + "            \"code\": \"122122\", \n"
      + "            \"name\": \"锡甲\", \n"
      + "            \"mark\": \"殿标\", \n"
      + "            \"parentCode\": 12212, \n"
      + "            \"parentName\": \"在武\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 86, \n"
      + "            \"code\": \"122123\", \n"
      + "            \"name\": \"锡榜\", \n"
      + "            \"mark\": \"登廷\", \n"
      + "            \"parentCode\": 12212, \n"
      + "            \"parentName\": \"在武\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 87, \n"
      + "            \"code\": \"122124\", \n"
      + "            \"name\": \"锡名\", \n"
      + "            \"mark\": \"品题\", \n"
      + "            \"parentCode\": 12212, \n"
      + "            \"parentName\": \"在武\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 88, \n"
      + "            \"code\": \"1221211\", \n"
      + "            \"name\": \"泰霖\", \n"
      + "            \"mark\": \"雨时\", \n"
      + "            \"parentCode\": 122121, \n"
      + "            \"parentName\": \"锡魁\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 89, \n"
      + "            \"code\": \"12212111\", \n"
      + "            \"name\": \"懋炎\", \n"
      + "            \"mark\": \"松火\", \n"
      + "            \"parentCode\": 1221211, \n"
      + "            \"parentName\": \"泰霖\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1920\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 90, \n"
      + "            \"code\": \"12212112\", \n"
      + "            \"name\": \"懋尤\", \n"
      + "            \"mark\": \"谷雨\", \n"
      + "            \"parentCode\": 1221211, \n"
      + "            \"parentName\": \"泰霖\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"民国13年，1924\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 91, \n"
      + "            \"code\": \"12212113\", \n"
      + "            \"name\": \"懋才\", \n"
      + "            \"mark\": \"才明\", \n"
      + "            \"parentCode\": 1221211, \n"
      + "            \"parentName\": \"泰霖\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"1936,殁年失考,无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 92, \n"
      + "            \"code\": \"12212114\", \n"
      + "            \"name\": \"懋清\", \n"
      + "            \"mark\": \"多能\", \n"
      + "            \"parentCode\": 1221211, \n"
      + "            \"parentName\": \"泰霖\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"1928,生子二 海 江\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 93, \n"
      + "            \"code\": \"12212115\", \n"
      + "            \"name\": \"懋仁\", \n"
      + "            \"mark\": \"多艺\", \n"
      + "            \"parentCode\": 1221211, \n"
      + "            \"parentName\": \"泰霖\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": \"1931 生子一\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 94, \n"
      + "            \"code\": \"12212116\", \n"
      + "            \"name\": \"懋礼\", \n"
      + "            \"mark\": \"多智\", \n"
      + "            \"parentCode\": 1221211, \n"
      + "            \"parentName\": \"泰霖\", \n"
      + "            \"sort\": 6, \n"
      + "            \"remark\": \"民国二十三年 1934\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 95, \n"
      + "            \"code\": \"12212117\", \n"
      + "            \"name\": \"懋智\", \n"
      + "            \"mark\": \"重北\", \n"
      + "            \"parentCode\": 1221211, \n"
      + "            \"parentName\": \"泰霖\", \n"
      + "            \"sort\": 7, \n"
      + "            \"remark\": \"1937，生子三 尧 舜 禹\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 96, \n"
      + "            \"code\": \"122121111\", \n"
      + "            \"name\": \"熙臣\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 12212111, \n"
      + "            \"parentName\": \"懋炎\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"细姑爷\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 97, \n"
      + "            \"code\": \"1221211111\", \n"
      + "            \"name\": \"培军\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 122121111, \n"
      + "            \"parentName\": \"熙臣\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"金牛哥\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 98, \n"
      + "            \"code\": \"122121121\", \n"
      + "            \"name\": \"熙改\", \n"
      + "            \"mark\": \"国珍\", \n"
      + "            \"parentCode\": 12212112, \n"
      + "            \"parentName\": \"懋尤\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1948 农业局副局长\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 99, \n"
      + "            \"code\": \"122121122\", \n"
      + "            \"name\": \"熙革\", \n"
      + "            \"mark\": \"国胜\", \n"
      + "            \"parentCode\": 12212112, \n"
      + "            \"parentName\": \"懋尤\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"1953 娶周火梅\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 100, \n"
      + "            \"code\": \"122121123\", \n"
      + "            \"name\": \"熙开\", \n"
      + "            \"mark\": \"国云\", \n"
      + "            \"parentCode\": 12212112, \n"
      + "            \"parentName\": \"懋尤\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"1955\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 101, \n"
      + "            \"code\": \"122121124\", \n"
      + "            \"name\": \"熙放\", \n"
      + "            \"mark\": \"国春\", \n"
      + "            \"parentCode\": 12212112, \n"
      + "            \"parentName\": \"懋尤\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"1964\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 102, \n"
      + "            \"code\": \"122121161\", \n"
      + "            \"name\": \"熙辉\", \n"
      + "            \"mark\": \"晓华\", \n"
      + "            \"parentCode\": 12212116, \n"
      + "            \"parentName\": \"懋礼\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 103, \n"
      + "            \"code\": \"122121162\", \n"
      + "            \"name\": \"熙煌\", \n"
      + "            \"mark\": \"年华\", \n"
      + "            \"parentCode\": 12212116, \n"
      + "            \"parentName\": \"懋礼\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 104, \n"
      + "            \"code\": \"1221121\", \n"
      + "            \"name\": \"泰兴\", \n"
      + "            \"mark\": \"松荣\", \n"
      + "            \"parentCode\": 122112, \n"
      + "            \"parentName\": \"锡瀛\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"嗣子\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 105, \n"
      + "            \"code\": \"12211211\", \n"
      + "            \"name\": \"懋喜\", \n"
      + "            \"mark\": \"宗兴\", \n"
      + "            \"parentCode\": 1221121, \n"
      + "            \"parentName\": \"泰兴\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 106, \n"
      + "            \"code\": \"12211212\", \n"
      + "            \"name\": \"懋槐\", \n"
      + "            \"mark\": \"宗德\", \n"
      + "            \"parentCode\": 1221121, \n"
      + "            \"parentName\": \"泰兴\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": null\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 107, \n"
      + "            \"code\": \"12211213\", \n"
      + "            \"name\": \"懋才\", \n"
      + "            \"mark\": \"宗才\", \n"
      + "            \"parentCode\": 1221121, \n"
      + "            \"parentName\": \"泰兴\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"民国二十七年\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 108, \n"
      + "            \"code\": \"12211214\", \n"
      + "            \"name\": \"懋润\", \n"
      + "            \"mark\": \"中喜\", \n"
      + "            \"parentCode\": 1221121, \n"
      + "            \"parentName\": \"泰兴\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"民国三十一年(1942)\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 109, \n"
      + "            \"code\": \"122112141\", \n"
      + "            \"name\": \"熙灿\", \n"
      + "            \"mark\": \"金灿\", \n"
      + "            \"parentCode\": 12211214, \n"
      + "            \"parentName\": \"懋润（中喜）\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1972\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 110, \n"
      + "            \"code\": \"1221211241\", \n"
      + "            \"name\": \"培菲\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 122121124, \n"
      + "            \"parentName\": \"熙放\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1987\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 112, \n"
      + "            \"code\": \"131\", \n"
      + "            \"name\": \"材圣\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13, \n"
      + "            \"parentName\": \"洪桂\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"乾隆四十六年 五子: 芬芳芹藻兰\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 113, \n"
      + "            \"code\": \"132\", \n"
      + "            \"name\": \"材仁\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13, \n"
      + "            \"parentName\": \"洪桂\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 114, \n"
      + "            \"code\": \"133\", \n"
      + "            \"name\": \"材申\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13, \n"
      + "            \"parentName\": \"洪桂\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 115, \n"
      + "            \"code\": \"134\", \n"
      + "            \"name\": \"材棠\", \n"
      + "            \"mark\": \"永学\", \n"
      + "            \"parentCode\": 13, \n"
      + "            \"parentName\": \"洪桂\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"乾隆六十年 二子：瀛香\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 116, \n"
      + "            \"code\": \"135\", \n"
      + "            \"name\": \"材悔\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13, \n"
      + "            \"parentName\": \"洪桂\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": \"嘉庆二年 生子二：发硌\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 117, \n"
      + "            \"code\": \"1341\", \n"
      + "            \"name\": \"烈瀛\", \n"
      + "            \"mark\": \"有芝\", \n"
      + "            \"parentCode\": 134, \n"
      + "            \"parentName\": \"材棠\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"道光七年 生子二：中田\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 118, \n"
      + "            \"code\": \"1342\", \n"
      + "            \"name\": \"烈香\", \n"
      + "            \"mark\": \"有兰\", \n"
      + "            \"parentCode\": 134, \n"
      + "            \"parentName\": \"材棠\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"道光十四年 生子五：恭宽信敏惠\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 119, \n"
      + "            \"code\": \"13421\", \n"
      + "            \"name\": \"在恭\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1342, \n"
      + "            \"parentName\": \"烈香\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"同治元年 生子一：德\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 120, \n"
      + "            \"code\": \"13422\", \n"
      + "            \"name\": \"在宽\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1342, \n"
      + "            \"parentName\": \"烈香\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 121, \n"
      + "            \"code\": \"13423\", \n"
      + "            \"name\": \"在信\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1342, \n"
      + "            \"parentName\": \"烈香\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 122, \n"
      + "            \"code\": \"13424\", \n"
      + "            \"name\": \"在敏\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1342, \n"
      + "            \"parentName\": \"烈香\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 123, \n"
      + "            \"code\": \"13425\", \n"
      + "            \"name\": \"在惠\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1342, \n"
      + "            \"parentName\": \"烈香\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 124, \n"
      + "            \"code\": \"134211\", \n"
      + "            \"name\": \"锡德\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13421, \n"
      + "            \"parentName\": \"在恭\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"光绪十八年 生子二：昌复\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 125, \n"
      + "            \"code\": \"1342111\", \n"
      + "            \"name\": \"泰昌\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 134211, \n"
      + "            \"parentName\": \"锡德\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"民国十八年（1929）生子三：根深稳\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 126, \n"
      + "            \"code\": \"1342112\", \n"
      + "            \"name\": \"泰复\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 134211, \n"
      + "            \"parentName\": \"锡德\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"民国二十一年（1932） 死于1956年，24岁无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 127, \n"
      + "            \"code\": \"13421111\", \n"
      + "            \"name\": \"懋根\", \n"
      + "            \"mark\": \"国兴\", \n"
      + "            \"parentCode\": 1342111, \n"
      + "            \"parentName\": \"泰昌\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"国兴叔 1957\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 128, \n"
      + "            \"code\": \"13421112\", \n"
      + "            \"name\": \"懋深\", \n"
      + "            \"mark\": \"国斌\", \n"
      + "            \"parentCode\": 1342111, \n"
      + "            \"parentName\": \"泰昌\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"二毛 1966\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 129, \n"
      + "            \"code\": \"13421113\", \n"
      + "            \"name\": \"懋稳\", \n"
      + "            \"mark\": \"再兴\", \n"
      + "            \"parentCode\": 1342111, \n"
      + "            \"parentName\": \"泰昌\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"澳侨 1970\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 130, \n"
      + "            \"code\": \"134211111\", \n"
      + "            \"name\": \"熙仁\", \n"
      + "            \"mark\": \"玉刚\", \n"
      + "            \"parentCode\": 13421111, \n"
      + "            \"parentName\": \"懋根\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1982\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 131, \n"
      + "            \"code\": \"1351\", \n"
      + "            \"name\": \"烈发\", \n"
      + "            \"mark\": \"有祥\", \n"
      + "            \"parentCode\": 135, \n"
      + "            \"parentName\": \"材悔\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"道光三年 生子一\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 132, \n"
      + "            \"code\": \"1352\", \n"
      + "            \"name\": \"烈硌\", \n"
      + "            \"mark\": \"有祯\", \n"
      + "            \"parentCode\": 135, \n"
      + "            \"parentName\": \"材悔\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"道光七年 生子三\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 133, \n"
      + "            \"code\": \"13511\", \n"
      + "            \"name\": \"在福\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1351, \n"
      + "            \"parentName\": \"烈发\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"咸丰六年 三子：廉亭儒\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 134, \n"
      + "            \"code\": \"135111\", \n"
      + "            \"name\": \"锡廉\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13511, \n"
      + "            \"parentName\": \"在福\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"光绪九年 无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 135, \n"
      + "            \"code\": \"135112\", \n"
      + "            \"name\": \"锡亭\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13511, \n"
      + "            \"parentName\": \"在福\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"光绪十四年 二子：云山\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 136, \n"
      + "            \"code\": \"135113\", \n"
      + "            \"name\": \"锡儒\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 13511, \n"
      + "            \"parentName\": \"在福\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"光绪十九年 殁于民国二十一年 生一子：发\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 137, \n"
      + "            \"code\": \"1351131\", \n"
      + "            \"name\": \"泰发\", \n"
      + "            \"mark\": \"记铭\", \n"
      + "            \"parentCode\": 135113, \n"
      + "            \"parentName\": \"锡儒\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"民国十八年(1929)\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 138, \n"
      + "            \"code\": \"13511311\", \n"
      + "            \"name\": \"懋瑞\", \n"
      + "            \"mark\": \"寿仪\", \n"
      + "            \"parentCode\": 1351131, \n"
      + "            \"parentName\": \"泰发\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1954 隔壁熟泥\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 139, \n"
      + "            \"code\": \"13511312\", \n"
      + "            \"name\": \"懋仪\", \n"
      + "            \"mark\": \"升仪\", \n"
      + "            \"parentCode\": 1351131, \n"
      + "            \"parentName\": \"泰发\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"1967 尔儿\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 140, \n"
      + "            \"code\": \"135113111\", \n"
      + "            \"name\": \"熙源\", \n"
      + "            \"mark\": \"祺君\", \n"
      + "            \"parentCode\": 13511311, \n"
      + "            \"parentName\": \"懋瑞\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1984\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 141, \n"
      + "            \"code\": \"135113121\", \n"
      + "            \"name\": \"熙碧\", \n"
      + "            \"mark\": \"碧泉\", \n"
      + "            \"parentCode\": 13511312, \n"
      + "            \"parentName\": \"懋仪\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1981\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 142, \n"
      + "            \"code\": \"135113122\", \n"
      + "            \"name\": \"熙泉\", \n"
      + "            \"mark\": \"玉泉\", \n"
      + "            \"parentCode\": 13511312, \n"
      + "            \"parentName\": \"懋仪\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"1985\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 143, \n"
      + "            \"code\": \"2\", \n"
      + "            \"name\": \"钟芳\", \n"
      + "            \"mark\": \"久也\", \n"
      + "            \"parentCode\": -1, \n"
      + "            \"parentName\": null, \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"康熙戊戌五十七年 生子四：任达庆仁\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 144, \n"
      + "            \"code\": \"21\", \n"
      + "            \"name\": \"洪任\", \n"
      + "            \"mark\": \"自远\", \n"
      + "            \"parentCode\": 2, \n"
      + "            \"parentName\": \"钟芳\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"乾隆辛酉 生子三：本抡棉\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 145, \n"
      + "            \"code\": \"22\", \n"
      + "            \"name\": \"洪达\", \n"
      + "            \"mark\": \"道远\", \n"
      + "            \"parentCode\": 2, \n"
      + "            \"parentName\": \"钟芳\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 146, \n"
      + "            \"code\": \"23\", \n"
      + "            \"name\": \"洪庆\", \n"
      + "            \"mark\": \"祥远\", \n"
      + "            \"parentCode\": 2, \n"
      + "            \"parentName\": \"钟芳\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"生子一：聘\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 147, \n"
      + "            \"code\": \"24\", \n"
      + "            \"name\": \"洪仁\", \n"
      + "            \"mark\": \"义远\", \n"
      + "            \"parentCode\": 2, \n"
      + "            \"parentName\": \"钟芳\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 148, \n"
      + "            \"code\": \"211\", \n"
      + "            \"name\": \"材本\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 21, \n"
      + "            \"parentName\": \"洪任\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"无子 立胞弟棉三子铭为嗣\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 149, \n"
      + "            \"code\": \"212\", \n"
      + "            \"name\": \"材抡\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 21, \n"
      + "            \"parentName\": \"洪任\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"无子 立胞弟棉四子功为嗣\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 150, \n"
      + "            \"code\": \"213\", \n"
      + "            \"name\": \"材棉\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 21, \n"
      + "            \"parentName\": \"洪任\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"乾隆庚子 生子四：闻绍铭功\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 151, \n"
      + "            \"code\": \"2131\", \n"
      + "            \"name\": \"烈闻\", \n"
      + "            \"mark\": \"祖望\", \n"
      + "            \"parentCode\": 213, \n"
      + "            \"parentName\": \"材棉\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"生子二： 遒礼\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 152, \n"
      + "            \"code\": \"2132\", \n"
      + "            \"name\": \"烈绍\", \n"
      + "            \"mark\": \"祖述\", \n"
      + "            \"parentCode\": 213, \n"
      + "            \"parentName\": \"材棉\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"生子二： 元高\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 153, \n"
      + "            \"code\": \"2133\", \n"
      + "            \"name\": \"烈铭\", \n"
      + "            \"mark\": \"祖发\", \n"
      + "            \"parentCode\": 213, \n"
      + "            \"parentName\": \"材棉\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"生子二：寿筹\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 154, \n"
      + "            \"code\": \"2134\", \n"
      + "            \"name\": \"烈功\", \n"
      + "            \"mark\": \"祖德\", \n"
      + "            \"parentCode\": 213, \n"
      + "            \"parentName\": \"材棉\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"生子三：光洋溢\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 155, \n"
      + "            \"code\": \"21321\", \n"
      + "            \"name\": \"在元\", \n"
      + "            \"mark\": \"得喜\", \n"
      + "            \"parentCode\": 2132, \n"
      + "            \"parentName\": \"烈绍\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"道光戊申 生子六：钧义礼智信春\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 156, \n"
      + "            \"code\": \"21322\", \n"
      + "            \"name\": \"在高\", \n"
      + "            \"mark\": \"金喜\", \n"
      + "            \"parentCode\": 2132, \n"
      + "            \"parentName\": \"烈绍\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"咸丰三年 生子四：勇强刚德\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 157, \n"
      + "            \"code\": \"213221\", \n"
      + "            \"name\": \"锡勇\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 21322, \n"
      + "            \"parentName\": \"在高\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"光绪六年 生子六：荣华富贵胜喜\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 158, \n"
      + "            \"code\": \"2132211\", \n"
      + "            \"name\": \"泰荣\", \n"
      + "            \"mark\": \"发兴\", \n"
      + "            \"parentCode\": 213221, \n"
      + "            \"parentName\": \"锡勇\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"光绪二十七年 生子一：宗\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 159, \n"
      + "            \"code\": \"2132212\", \n"
      + "            \"name\": \"泰华\", \n"
      + "            \"mark\": \"发美\", \n"
      + "            \"parentCode\": 213221, \n"
      + "            \"parentName\": \"锡勇\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"生子二：甫田\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 160, \n"
      + "            \"code\": \"2132213\", \n"
      + "            \"name\": \"泰富\", \n"
      + "            \"mark\": \"祥发\", \n"
      + "            \"parentCode\": 213221, \n"
      + "            \"parentName\": \"锡勇\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"生子二：鸿国\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 161, \n"
      + "            \"code\": \"2132214\", \n"
      + "            \"name\": \"泰贵\", \n"
      + "            \"mark\": \"发喜\", \n"
      + "            \"parentCode\": 213221, \n"
      + "            \"parentName\": \"锡勇\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"无子，立胞弟喜二子水为嗣\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 162, \n"
      + "            \"code\": \"2132215\", \n"
      + "            \"name\": \"泰胜\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 213221, \n"
      + "            \"parentName\": \"锡勇\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": \"无子\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 163, \n"
      + "            \"code\": \"2132216\", \n"
      + "            \"name\": \"泰喜\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 213221, \n"
      + "            \"parentName\": \"锡勇\", \n"
      + "            \"sort\": 6, \n"
      + "            \"remark\": \"民国十四年，生子二：仁水\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 164, \n"
      + "            \"code\": \"21322161\", \n"
      + "            \"name\": \"懋仁\", \n"
      + "            \"mark\": \"绍仁\", \n"
      + "            \"parentCode\": 2132216, \n"
      + "            \"parentName\": \"泰喜\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"开超市的\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 165, \n"
      + "            \"code\": \"21322162\", \n"
      + "            \"name\": \"懋水\", \n"
      + "            \"mark\": \"绍水\", \n"
      + "            \"parentCode\": 2132216, \n"
      + "            \"parentName\": \"泰喜\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"放鸭子的\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 166, \n"
      + "            \"code\": \"213221611\", \n"
      + "            \"name\": \"熙洪\", \n"
      + "            \"mark\": \"洪峰\", \n"
      + "            \"parentCode\": 21322161, \n"
      + "            \"parentName\": \"懋仁\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1982\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 167, \n"
      + "            \"code\": \"213221612\", \n"
      + "            \"name\": \"熙锋\", \n"
      + "            \"mark\": \"熙锋\", \n"
      + "            \"parentCode\": 21322161, \n"
      + "            \"parentName\": \"懋仁\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"1986\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 168, \n"
      + "            \"code\": \"21322131\", \n"
      + "            \"name\": \"懋鸿\", \n"
      + "            \"mark\": \"高举\", \n"
      + "            \"parentCode\": 2132213, \n"
      + "            \"parentName\": \"泰富\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"无子\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 169, \n"
      + "            \"code\": \"21322132\", \n"
      + "            \"name\": \"懋国\", \n"
      + "            \"mark\": \"四女\", \n"
      + "            \"parentCode\": 2132213, \n"
      + "            \"parentName\": \"泰富\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"民国三十三年\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 171, \n"
      + "            \"code\": \"213221321\", \n"
      + "            \"name\": \"熙文\", \n"
      + "            \"mark\": \"亚文\", \n"
      + "            \"parentCode\": 21322132, \n"
      + "            \"parentName\": \"懋国\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1978\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 172, \n"
      + "            \"code\": \"213221322\", \n"
      + "            \"name\": \"熙君\", \n"
      + "            \"mark\": \"亚君\", \n"
      + "            \"parentCode\": 21322132, \n"
      + "            \"parentName\": \"懋国\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"1981\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 173, \n"
      + "            \"code\": \"11212141\", \n"
      + "            \"name\": \"楙福\", \n"
      + "            \"mark\": \"祖光\", \n"
      + "            \"parentCode\": 1121214, \n"
      + "            \"parentName\": \"泰尙\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"民国十四年 生子二：良桂\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 174, \n"
      + "            \"code\": \"11212142\", \n"
      + "            \"name\": \"楙禄\", \n"
      + "            \"mark\": \"祖神\", \n"
      + "            \"parentCode\": 1121214, \n"
      + "            \"parentName\": \"泰尙\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 175, \n"
      + "            \"code\": \"11212143\", \n"
      + "            \"name\": \"楙寿\", \n"
      + "            \"mark\": \"祖谷\", \n"
      + "            \"parentCode\": 1121214, \n"
      + "            \"parentName\": \"泰尙\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 176, \n"
      + "            \"code\": \"112121411\", \n"
      + "            \"name\": \"熙良\", \n"
      + "            \"mark\": \"桂生\", \n"
      + "            \"parentCode\": 11212141, \n"
      + "            \"parentName\": \"楙福\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"民国三十四年 生子二花友\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 177, \n"
      + "            \"code\": \"112121412\", \n"
      + "            \"name\": \"熙桂\", \n"
      + "            \"mark\": \"春生\", \n"
      + "            \"parentCode\": 11212141, \n"
      + "            \"parentName\": \"楙福\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"建华父亲\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 178, \n"
      + "            \"code\": \"1211\", \n"
      + "            \"name\": \"烈瑞\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121, \n"
      + "            \"parentName\": \"材达\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"生子二：勤勋\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 179, \n"
      + "            \"code\": \"1212\", \n"
      + "            \"name\": \"烈与\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121, \n"
      + "            \"parentName\": \"材达\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"生子三：桢楠杞\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 180, \n"
      + "            \"code\": \"1213\", \n"
      + "            \"name\": \"烈兴\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121, \n"
      + "            \"parentName\": \"材达\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"生子一：位\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 181, \n"
      + "            \"code\": \"1214\", \n"
      + "            \"name\": \"烈仁\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121, \n"
      + "            \"parentName\": \"材达\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"生子三：洲源\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 182, \n"
      + "            \"code\": \"1215\", \n"
      + "            \"name\": \"烈声\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121, \n"
      + "            \"parentName\": \"材达\", \n"
      + "            \"sort\": 5, \n"
      + "            \"remark\": \"生子四：铨銶铣钧\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 183, \n"
      + "            \"code\": \"1216\", \n"
      + "            \"name\": \"烈珍\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121, \n"
      + "            \"parentName\": \"材达\", \n"
      + "            \"sort\": 6, \n"
      + "            \"remark\": \"生子三：睿爵光\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 184, \n"
      + "            \"code\": \"12151\", \n"
      + "            \"name\": \"在铨\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1215, \n"
      + "            \"parentName\": \"烈声\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"生子一：廉\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 185, \n"
      + "            \"code\": \"12152\", \n"
      + "            \"name\": \"在銶\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1215, \n"
      + "            \"parentName\": \"烈声\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"无子，立弟钧长子书为嗣\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 186, \n"
      + "            \"code\": \"12153\", \n"
      + "            \"name\": \"在铣\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 1215, \n"
      + "            \"parentName\": \"烈声\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"无子，立弟钧三子茂为嗣\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 187, \n"
      + "            \"code\": \"12154\", \n"
      + "            \"name\": \"在钧\", \n"
      + "            \"mark\": \"新映\", \n"
      + "            \"parentCode\": 1215, \n"
      + "            \"parentName\": \"烈声\", \n"
      + "            \"sort\": 4, \n"
      + "            \"remark\": \"生子三：书凤茂\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 188, \n"
      + "            \"code\": \"121511\", \n"
      + "            \"name\": \"锡廉\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 12151, \n"
      + "            \"parentName\": \"在铨\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"光绪四年 生二子：智佑\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 189, \n"
      + "            \"code\": \"1215111\", \n"
      + "            \"name\": \"泰智\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121511, \n"
      + "            \"parentName\": \"锡廉\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"光绪三十二年 早卒无子\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 190, \n"
      + "            \"code\": \"1215112\", \n"
      + "            \"name\": \"泰佑\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121511, \n"
      + "            \"parentName\": \"锡廉\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"民国二年 早卒无子\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 191, \n"
      + "            \"code\": \"121541\", \n"
      + "            \"name\": \"锡书\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 12154, \n"
      + "            \"parentName\": \"在钧\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"生三子：楷高明，三子均无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 192, \n"
      + "            \"code\": \"121542\", \n"
      + "            \"name\": \"锡凤\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 12154, \n"
      + "            \"parentName\": \"在钧\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"光绪十四年 早亡\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 193, \n"
      + "            \"code\": \"1215411\", \n"
      + "            \"name\": \"泰楷\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121541, \n"
      + "            \"parentName\": \"锡书\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"光绪三十三年 殁于民国二十七年 无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 194, \n"
      + "            \"code\": \"1215412\", \n"
      + "            \"name\": \"泰高\", \n"
      + "            \"mark\": \"水金\", \n"
      + "            \"parentCode\": 121541, \n"
      + "            \"parentName\": \"锡书\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"民国四年 殁于民国二十三年 无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 195, \n"
      + "            \"code\": \"1215413\", \n"
      + "            \"name\": \"泰明\", \n"
      + "            \"mark\": \"明弟\", \n"
      + "            \"parentCode\": 121541, \n"
      + "            \"parentName\": \"锡书\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"民国十三年 无后\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 196, \n"
      + "            \"code\": \"121543\", \n"
      + "            \"name\": \"锡茂\", \n"
      + "            \"mark\": \"炎松\", \n"
      + "            \"parentCode\": 12154, \n"
      + "            \"parentName\": \"在钧\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"光绪二十年 生子一：斌\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 197, \n"
      + "            \"code\": \"1215431\", \n"
      + "            \"name\": \"泰斌\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 121543, \n"
      + "            \"parentName\": \"锡茂\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"民国11年 生子三：忠良将\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 198, \n"
      + "            \"code\": \"12154311\", \n"
      + "            \"name\": \"懋忠\", \n"
      + "            \"mark\": \"广生\", \n"
      + "            \"parentCode\": 1215431, \n"
      + "            \"parentName\": \"泰斌\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"民国三十岁年 生子二：猛刚\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 199, \n"
      + "            \"code\": \"12154312\", \n"
      + "            \"name\": \"懋良\", \n"
      + "            \"mark\": \"连生\", \n"
      + "            \"parentCode\": 1215431, \n"
      + "            \"parentName\": \"泰斌\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"民国三十七年 生子二：勇强\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 200, \n"
      + "            \"code\": \"12154313\", \n"
      + "            \"name\": \"懋将\", \n"
      + "            \"mark\": \"谱生\", \n"
      + "            \"parentCode\": 1215431, \n"
      + "            \"parentName\": \"泰斌\", \n"
      + "            \"sort\": 3, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 201, \n"
      + "            \"code\": \"121543111\", \n"
      + "            \"name\": \"熙猛\", \n"
      + "            \"mark\": \"志权\", \n"
      + "            \"parentCode\": 12154311, \n"
      + "            \"parentName\": \"懋忠\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1963\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 202, \n"
      + "            \"code\": \"121543112\", \n"
      + "            \"name\": \"熙刚\", \n"
      + "            \"mark\": \"攀峰\", \n"
      + "            \"parentCode\": 12154311, \n"
      + "            \"parentName\": \"懋忠\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"1966\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 203, \n"
      + "            \"code\": \"121543121\", \n"
      + "            \"name\": \"熙勇\", \n"
      + "            \"mark\": \"志勇\", \n"
      + "            \"parentCode\": 12154312, \n"
      + "            \"parentName\": \"懋良\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"1970\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 204, \n"
      + "            \"code\": \"121543122\", \n"
      + "            \"name\": \"熙强\", \n"
      + "            \"mark\": \"峰峰\", \n"
      + "            \"parentCode\": 12154312, \n"
      + "            \"parentName\": \"懋良\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"1982\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 205, \n"
      + "            \"code\": \"112112311\", \n"
      + "            \"name\": \"光明-翘嘴\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 11211231, \n"
      + "            \"parentName\": \"楙潜\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"翘嘴\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 206, \n"
      + "            \"code\": \"1121123111\", \n"
      + "            \"name\": \"利祥\", \n"
      + "            \"mark\": \"\", \n"
      + "            \"parentCode\": 112112311, \n"
      + "            \"parentName\": \"光明-翘嘴\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"五百九\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 207, \n"
      + "            \"code\": \"112112331\", \n"
      + "            \"name\": \"熙明\", \n"
      + "            \"mark\": \"熙明\", \n"
      + "            \"parentCode\": 11211233, \n"
      + "            \"parentName\": \"楙贵\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"办席的\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 208, \n"
      + "            \"code\": \"1121123311\", \n"
      + "            \"name\": \"陪庆\", \n"
      + "            \"mark\": \"文潮\", \n"
      + "            \"parentCode\": 112112331, \n"
      + "            \"parentName\": \"熙明\", \n"
      + "            \"sort\": 1, \n"
      + "            \"remark\": \"\"\n"
      + "        }, \n"
      + "        {\n"
      + "            \"id\": 209, \n"
      + "            \"code\": \"112112332\", \n"
      + "            \"name\": \"熙荒\", \n"
      + "            \"mark\": \"熙荒\", \n"
      + "            \"parentCode\": 11211233, \n"
      + "            \"parentName\": \"楙贵\", \n"
      + "            \"sort\": 2, \n"
      + "            \"remark\": \"三岁\"\n"
      + "        }\n"
      + "]";


  List<FamilyTreeNode> datas;
  private Map<String, List<FamilyTreeNode>> treeNodeGroups;
  private List<FamilyTreeNode> subRootDtos;
  private FamilyTreeNode root;



  @BeforeAll
  public  void test1() {
    datas = JsonUtil.readListValue(jsonStr, FamilyTreeNode.class);
    datas.forEach(x-> {
//      x.setId(Long.valueOf(x.getCode()));
      x.setName(new StringBuffer(x.getName()).append("-").append(x.getMark()).toString());
    });//转long

    treeNodeGroups = datas.stream().collect(
        Collectors.groupingBy(x-> x.getParentCode()));

    //按sort字段排序
    for (Entry<String, List<FamilyTreeNode>> longListEntry : treeNodeGroups.entrySet()) {
      List<FamilyTreeNode> treeNodes = longListEntry.getValue();
      Collections.sort(treeNodes, Comparator.comparingInt(FamilyTreeNode::getSort));
    }

    //二级根
    subRootDtos = datas.stream().filter(x -> "-1".equals(x.getParentCode())).sorted(
        Comparator.comparingInt(FamilyTreeNode::getSort)).collect(Collectors.toList());

    //虚拟一个root
    root = new FamilyTreeNode().setId(-1L).setName("root").setParentCode("-100");
    root.setChildren(subRootDtos);
  }

  public void processBuildTree(FamilyTreeNode node) {

    List<FamilyTreeNode> childrenNodes = treeNodeGroups.getOrDefault(node.getCode(), Collections.EMPTY_LIST);
    node.setChildren(childrenNodes);

    for (FamilyTreeNode child : node.getChildren()) {
      processBuildTree(child);
    }
  }

  @Test
  public void buildTree() {
    for (FamilyTreeNode subRootDto : subRootDtos) {
      processBuildTree(subRootDto);
    }


    LOGGER.error("{}", JsonUtil.writeValueAsString(root, true));
  }

  //{id: 100, name: 'flare', value: 123, pid: 0},


  @Test
  public void buildTree1() {
    List<FamilyTreeNodeNew> nodeNewList = datas.stream().map(x -> {
      FamilyTreeNodeNew treeNodeNew = new FamilyTreeNodeNew();
      treeNodeNew.setId(x.getId());
      treeNodeNew.setName(x.getName());
      treeNodeNew.setValue(x.getMark());
      treeNodeNew.setPid(Long.valueOf(x.getParentCode()));
      return treeNodeNew;
    }).collect(Collectors.toList());
    LOGGER.error("{}", JsonUtil.writeValueAsString(nodeNewList, true));

  }

}
